# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts
COPY src ./src
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy package.json and install production dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy built files
COPY --from=builder /app/dist ./dist

EXPOSE 8888
CMD ["node", "dist/index.js"]
